# Generated by Django 4.2.5 on 2023-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatingUsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('zona', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(max_length=50)),
                ('puntaje', models.IntegerField()),
                ('tarjcred', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Brunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('zona', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(max_length=50)),
                ('puntaje', models.IntegerField()),
                ('tarjcred', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('zona', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(max_length=50)),
                ('puntaje', models.IntegerField()),
                ('tarjcred', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Merienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('zona', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(max_length=50)),
                ('puntaje', models.IntegerField()),
                ('tarjcred', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
        migrations.DeleteModel(
            name='Nombre',
        ),
        migrations.DeleteModel(
            name='Puntaje',
        ),
        migrations.DeleteModel(
            name='TarjCred',
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
