# Generated by Django 4.2.5 on 2023-10-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatingUsApp', '0002_almuerzo_brunch_cena_merienda_delete_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almuerzo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='almuerzo',
            name='zona',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='brunch',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='brunch',
            name='zona',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cena',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cena',
            name='zona',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='merienda',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='merienda',
            name='zona',
            field=models.CharField(max_length=30),
        ),
    ]
